name: app_genesis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  google_fonts: ^6.2.1
  toastification: ^2.2.0
  image_picker: ^1.0.8
  http: ^1.0.0
  provider: ^6.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: 'Popin'
      fonts:
        - asset: 'assets/fonts/pop.ttf'